load("//bazel/rules/cxx:rules.bzl", "cxx_static_library")

cxx_static_library(
    name = "func1",
    srcs = [
        "func1.cpp",
    ],
    hdrs = [
        "func1.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
